### ISSUE TITLE
[quiz] What do you hope to get out of the course?

### ISSUE THREAD

**Issue by sr320** [sr320/fish546-2015#1]

**Comment by jldimond** [comment]
I'm hoping to get more comfortable with bioinformatic techniques and software. And I am really looking forward to have an opportunity to start analyzing some data and make some progress on my project and (eventually) a paper.

**Comment by kubu4** [comment]
I'm hoping to help solidify all the concepts of RNA-Seq in a more cohesive framework in my mind, as well as strengthening my existing computing "skills."

**Comment by lisa418** [comment]
I hope to become less intimidated by computer jargon/script and become more proficient at manipulating and analyzing large data sets. I also aim to have a solid methods and results section completed for our black abalone transcriptome manuscript.

**Comment by willking2** [comment]
Broad
-Begin to develop bioinformatics skill set (what resources are out there? what are the key tools?)
-Become comfortable in discussing, analyzing, thinking about molecular ecology
-Gain a solid enough understanding of bioinformatics to determine how it might fit into my dissertation work, if at all

Specific
-What's known about barnacle genetics?
-A product that contributes to a paper down the road
-Get to know people with whom I can exchange ideas about this kind of stuff

**Comment by jheare** [comment]
With a working procedure for processing and analzying the RAD-Seq data we have created as well as improve my technical skills with multiple programs and languages. I also want to improve my reproducibility by improving how I write code/ procedures so they can be used by anyone.
