### ISSUE TITLE
[quiz] Change of Practice

### ISSUE THREAD

**Issue by sr320** [sr320/fish546-2015#10]
In last week's reading there were several suggestions for best practices with both descriptions and rationale.

What are two practices you think are important and hope to implement in you data analysis workflow?

**Comment by willking2** [comment]
1) Scripting to let the computer do the work. This includes making stats outputs and figures that update automatically. 
2) Documenting everything in readme files. I've started doing this with my own files but would like to improve the habit.

**Comment by jheare** [comment]
1) Commenting out where data, scripts, and programs came from including version number, date of download, URL, and operating system, to create more accurately reproducible results for myself and other researchers. 

2) To work strictly with repository to improve versioning of scripts. Keeping scripts clean, easily readable and modifiable, while always having a copy to go back to or share.

**Comment by kubu4** [comment]
1. Set up programs and workflows that simplify repeatability and minimize "hands-on" computing.
2. Implementing program tests/checks where possible.  This will help reduce "silent errors".

**Comment by lisa418** [comment]
1. Proper documentation and better file organization to improve reproducibility
2. Using scripts to make tables/figures so outputs can be easily re-run and visualized

**Comment by jldimond** [comment]
-Document everything. I could certainly use some improvement in this area.

-Let the computer work for you. I'm sure I will appreciate this when it comes time to do more complex analyses like assembling a transcriptome or something.
