### ISSUE TITLE
Understanding relative paths?

### ISSUE THREAD

**Issue by kubu4** [sr320/fish546-2015#11]
Interesting point in reading regarding how relative paths are more user-friendly when working with collaborators (or, sharing code).

Can we discuss/play around with this in class tomorrow?  I'm not sure I fully understand how they work.

**Comment by kubu4** [comment]
P.S.  I can't seem to add a label to this (help needed).

**Comment by lisa418** [comment]
I agree! I'm still not completely clear on what the actual difference is between relative and absolute paths.

**Comment by sr320** [comment]
Will go over today

—
Steven Roberts

**Comment by sr320** [comment]
covered in class...
