### ISSUE TITLE
[quiz] Directory structure and naming conventions.

### ISSUE THREAD

**Issue by sr320** [sr320/fish546-2015#12]
Describe (or show) the directory structure you will be using for your project and your planned naming conventions. 

Also add this _game plan_ to the readme file in your main directory. :+1:

**Comment by willking2** [comment]
This is what I have so far. I know what each directory is for, but not sure about the specific types of files (and file extensions) that will go in most of them. Will update in readme.md of main directory (Nlap-ano) as I figure it out.

\Nlap-ano
- readme.md
- \data
  - readme.md
  - N_lapillus.fa
  - uniprot.fasta
- \scripts
  - readme.md
- \ntbk
  - readme.md
- \analyses
  - readme.md

![2015-01-14 22 44 58](https://cloud.githubusercontent.com/assets/10429653/5753525/a3220ece-9c3f-11e4-816a-3cdce8c9410b.jpg)

**Comment by jheare** [comment]
So far my repository uses this organization (generic file names unless calling specific file):

Fish546-Jake/
~/README.md
~/.gitattributes

/nb
~/.ipynb_checkpoints/
~/project process related notebook.ipynb

/data
~/month created process barcode version number.csv
~/process_radtags.log

Outside of the repository I am using a /radseqdata/ directory on local machines to house the larger data files that cannot be stored on github but are needed for the coding to work. 

Though I do need to do some minor house cleaning of test files which I may include in a subdirectory called 

/test

Also If I produce or download any scripts to use in a process they will be included in a directory called

/scripts

**Comment by jldimond** [comment]
fish546-2105/
Data/
--Ahya/
--Amil/
--Apalm/
--Mfav/
--Spist/
--Pdam/
Analyses/
Scripts/
nb/

**Comment by lisa418** [comment]
fish546-2015/
analyses/
data/
ms/
nb/
scripts/
