### ISSUE TITLE
Speed up your BLAST jobs

### ISSUE THREAD

**Issue by kubu4** [sr320/fish546-2015#13]
Killer tip for people using BLAST.

Add the following option when running any BLAST job:

-num_threads 16

This will instruct your computer to maximize the CPU usage.  The default setting is to only use a single CPU thread, which ends up being pretty slow.

The only "catch" with maxing out your CPU usage is that the computer you run BLAST on will respond much more slowly to any other tasks you try to do simultaneously (like browse the web).

Here's an example BLAST command that utilizes the -num_threads flag:

blastn -task blastn -query /home/samb/BioinformaticsTools/ncbi-blast-2.2.29+/queries/AllAbDenovo7118contigs.fa -db RickettsiaGBnt20140228 -outfmt 6 -max_target_seqs 1 -num_threads 16 -out /home/samb/BioinformaticsTools/ncbi-blast-2.2.29+/outputs/test.txt

**Comment by sr320** [comment]
Note you can also do any number - so if you have 6 cpus, you could use 4 etc.

Q - Is 16 really max or is it just most persons don't have more than 16 cpus (ie -16 would only use 1/2 on 32 cpu machine?

**Comment by kubu4** [comment]
The latter.

**Comment by willking2** [comment]
My blastx has been going for about an hour and the .tab file is currently at 41KB. Is this normal?

**Comment by kubu4** [comment]
Too many variables to give advice regarding how long a BLAST job should take.  Depends on:
processor(s) and how many are being utilized
RAM (installed on computer AND how much is available to the BLAST program)
no. of query sequences
no. of database sequences

**Comment by sr320** [comment]
But generally Will - given I presume you are doing a whole transcriptome- it could easily take +24 hour on standard pc.   Maybe Tuesday you all can talk about running on hummingbird 

—
Steven Roberts

**Comment by willking2** [comment]
Gotcha. Thanks
