### ISSUE TITLE
include uniprot in project structure/github?

### ISSUE THREAD

**Issue by willking2** [sr320/fish546-2015#14]
To make the project as self-contained as possible, I put my uniprot fasta file and all the BLAST files in my project structure. But when I try to sync my local directory with the online one, GitHub gets stuck. I'm presuming that's because those files are too large (uniprot is around 260,000 KB). 

Should I not include uniprot and BLAST in my directory? Or find a place with faster internet?

(sorry if this is answered in BDS, haven't finished reading yet)

**Comment by sr320** [comment]
You cannot have a file over 100 MB uploaded to GitHub 

—
Steven Roberts
