### ISSUE TITLE
[quiz] Programs to search for sequence motif in genome

### ISSUE THREAD

**Issue by sr320** [sr320/fish546-2015#15]
Based on you reading what are 3 programs that can be used from the shell to search for a given motif (ie ACHGTGATCCAA) in a genome?

Which one is the fastest?

**Comment by lisa418** [comment]
grep = fastest
sed
awk

**Comment by jheare** [comment]
grep is fastest but must be installed in windows to be useful for windows machines
sed has limited native functionality in windows but can be useful for searching
gawk is the windows version of awk and allows for more functionality than normal awk though it is slower than grep on windows.

**Comment by willking2** [comment]
![image](https://cloud.githubusercontent.com/assets/10429653/5870079/d61554ea-a279-11e4-93c9-ea10f5584890.png)
