### ISSUE TITLE
[quiz] Methods section

### ISSUE THREAD

**Issue by sr320** [sr320/fish546-2015#16]
This week everyone needs to complete a methods section that would include all analysis done to date.
Please add the url for your md file below and in addition, paste the contents of your methods.md file.

Remember it needs to be written in a manner that someone else could reproduce.

**Comment by willking2** [comment]
**https://github.com/willking2/fish546_W15/blob/master/nlap-ano/methods.md**

To annotate the transcriptome of the dog whelk, _Nucella lapillus_, I used Blastx v 2.2.29+ to annotate contigs against the UniProtKB Swiss-prot database, applying an E-value cut-off of 1E-20.

The transcriptome of _N. lapillus_ was obtained from the Dryad Digital Repository (http://dx.doi.org/10.5061/dryad.610dd) specified in Chu et al. (2014). Blastx was downloaded from the National Center for Biotechnology Information website (http://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Web&PAGE_TYPE=BlastDocs&DOC_TYPE=Download) as a stand-alone version. The UniProtKB Swiss-prot database was downloaded from the Universal Protein Resource website (http://www.uniprot.org/downloads). For Blastx, the query sequence was the transcriptome of _N. lapillus_ and the database for comparison was the UniprotKB Swiss-prot database.

**Comment by jheare** [comment]
I wrote a short explanation of what I've done so far with processing the radtags. I also included a link to my notebook to show the workflow of how to do the bioinformatics portion of the project. I then concluded with a short explanation of what the Seeb lab told me about the DNA quality and its respect to the low number of ambiguous barcodes. I'll update this methods file as I produce more workflows for various procedures in STACKS. 

[METHODS.md](https://github.com/jheare/Fish546-Jake/blob/master/METHODS.md)

**Comment by jldimond** [comment]
https://github.com/jldimond/fish546-2015/blob/master/Analyses/Methods.md

Note that I included things I have not done yet...

**Comment by lisa418** [comment]
https://github.com/lisa418/fish546-2015/blob/master/ms/methods.md

**Comment by kubu4** [comment]
https://github.com/kubu4/fish546_2015/blob/master/methods.md

###Sequence Quality Assessment

Six Illumina (HiSeq2500) FASTQ sequencing files (three biological replicates each, from pre- and post-heat shock) were analyzed with FASTQC (v0.11.2).  

> Need to determine what to do with output from FASTQC - just describe the results?
> 
> What constitutes "passing" qualities?

All FASTQ files were processed with FASTX Trimmer (v0.0.13.2) and re-evaluated with FASTQC.

###Sequence Alignment

A Bowtie (v2.1.0) sequence index was created using the Crassostrea gigas genome FASTA file from Ensembl: Crassostrea_gigas.GCA_000297895.1.24.dna_sm.genome.fa. TopHat (v2.0.13.OSX_x86_64), using default parameters was used to align the reads to the Bowtie sequence index.  The two sets of reads (pre- and post-heat shock) were aligned separately. The TopHat output file, accepted_hits.bam, was converted to some file type

> Should I have a supplemental file that lists the default parameters?
> 
> Should I have done separate alignments for each FASTQ file to represent the biological replicates?
> 
> i.e. at what stage should the data be "pooled" into the two different treatments?
> 
> Regardless, should probably align all separately to assess individual variation within treatments...
> 
> Need to figure out what to do with all the bed files now.
> 
> Will I be doing anything with splice junction info?

###Sequence Annotation

Sequences were identified with blastx (v?) by comparing them to the Swiss-Prot (downloaded DATE) protein database. Annotated sequences were further annotated using gene ontologies (GO) to categorize putative functions.

###Differential Gene Expression

> Have to figure out what to for this
