### ISSUE TITLE
download data in command line to hummingbird

### ISSUE THREAD

**Issue by willking2** [sr320/fish546-2015#17]
I'm working in hummingbird, srlab/willbigdata directory. I would like to download the [uniprot swiss-prot dataset](http://www.uniprot.org/downloads) into the /willbigdata directory:

`hummingbird:willbigdata srlab$ curl ftp://ftp.uniprot.org/pub/databases/uniprotcurrent_release/knowledgebase/complete/uniprot_sprot.fasta.gz`

However, when I try to use curl, it says the server denied me:

`curl: (9) Server denied you to change to the given directory`

Tried looking it up online, but can't figure it out. Thoughts? Thanks

**Comment by kubu4** [comment]
That URL seems to missing a slash after the "uniprot" before "current_release".  Here's the URL that you want to use (I've tested it three different ways):

ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.fasta.gz

**Comment by willking2** [comment]
Just tried it twice using URL you provided. Both times, after I hit enter, screen runs through crazy text for a while and then ends with "PUTTYPUTTYPUTTY". Here's some of it: 

`!z▒▒l▒UX▒▒R▒9s▒▒▒w▒F
*▒$+6Sx▒:▒▒▒▒▒cy▒Q▒7▒▒▒▒4▒V▒▒Cu`
▒:▒▒\▒▒▒A▒'0▒▒iq▒▒f▒▒.▒=▒vK▒▒▒(~r▒1:▒▒▒▒▒3sȣ/▒pqMG▒z▒▒▒z▒▒▒▒▒▒▒dW▒b▒C▒n▒v̟}▒A
▒䱚?k▒a▒\▒X▒▒P▒▒▒
▒ѵܚ▒▒3▒▒▒▒b@!.ch▒$I▒/X▒b▒-̿▒▒▒   ݚ▒▒▒▒o▒▒ļ▒▒'▒߱▒Í▒▒e}▒▒▒p▒\* ▒g▒<▒▒▒▒▒▒L▒G▒Ȏ▒▒▒▒▒▒▒▒▒▒▒▒▒7▒▒?i▒cwg▒Ý▒7▒▒▒▒k▒i5▒f▒▒▒▒▒_2▒f▒N▒▒w7▒3▒1▒▒k▒▒w▒▒߬▒▒▒▒▒}▒/▒yd▒inV▒ߚ▒▒▒7▒▒▒▒_Y▒▒▒v▒Q▒▒:▒▒ÇO▒▒_\▒▒V▒▒▒▒▒͗▒▒▒▒▒▒_▒|}▒▒▒▒O_▒8z▒▒e▒▒[▒l▒▒,▒B▒▒EKVώ▒▒▒A▒̠J▒▒▒E▒▒a▒-[ ▒G▒k`▒▒Sڼ▒F▒▒▒-▒▒▒▒6}▒?1▒▒▒7▒G▒<▒▒7▒▒▒▒▒▒▒W▒3▒|▒◫▒/▒▒▒▒▒▒▒▒×▒▒'▒_>▒8▒▒g%▒▒,▒▒:▒▒▒y]▒▒▒wwuq▒~ʱb▒z▒'▒Z▒N%▒▒M▒,.o▒1▒óW\▒▒▒x▒▒▒/6▒_.n.▒ܝ▒P▒▒▒Ç]▒▒▒0▒▒o~▒▒▒▒plx▒?0[▒▒8M▒▒▒▒▒:▒r`▒▒r8C2▒K▒▒▒▒▒▒c^;▒▒▒▒{߾▒|▒▒<▒▒▒׏▒▒o▒?\▒▒r▒▒▒▒▒▒Q▒▒'{n6▒m6▒s▒r[▒[^▒<▒'▒▒3▒▒f▒ZCSH▒o0▒pg▒ ▒▒g▒▒▒▒/▒▒ś▒▒▒▒/▒\▒▒▒▒▒▒'▒'▒▒▒▒▒M&▒4x▒▒{!▒▒q|nO▒]\▒"hY▒▒`Eݲ▒▒N▒#▒<V▒t;▒<▒▒▒▒=▒▒▒▒_a=*▒\▒▒▒Q_7W▒▒▒/▒▒\\]▒▒▒▒▒▒x}vvvD▒▒Y▒▒▒▒:▒v"▒ ▒▒▒B▒`MJ▒▒X▒j▒5▒f]▒a^]<▒ϭ▒▒u▒▒㗳$▒4▒▒5▒O▒▒طC▒▒՗▒͇▒ϛK▒x▒▒▒o.▒_t▒▒<▒▒98z▒▒▒▒S▒\▒-p,1▒▒"▒Ӛ▒▒Ԉ▒▒/V▒▒X▒▒*
GG▒g▒"▒-▒Ѵ▒%'▒]▒Y▒j▒)▒▒▒▒(▒u▒▒▒▒▒i▒▒▒
▒v▒▒,▒}▒)▒S▒▒▒ZL%)*▒خ▒▒d▒ojݲ'▒i▒@▒▒▒I▒;e▒rX▒▒\▒?<y▒A▒▒B6▒▒▒▒▒▒▒▒▒▒O.▒m▒▒▒{▒▒▒▒6▒▒▒▒▒ۻ▒▒o▒▒▒𜒝nK&"▒▒▒▒q▒▒1P▒▒j▒▒(▒ao      [▒▒"6칓
                                               ▒F▒▒▒q▒▒/▒S▒Af
^▒▒▒▒▒
 v3j▒▒▒h▒e
^f43▒=▒▒▒A▒V6F▒ê▒▒s▒`▒[B▒▒/O▒▒^▒ۓ▒OOo▒▒|▒▒▒bv▒▒[▒S▒▒▒▒▒؋뫋?▒ܼ'|`▒▒▒mS▒▒A▒▒,C'2fXn▒▒xT▒L▒▒▒Mr
           2G▒2▒▒3A▒▒▒▒▒O▒▒▒QBXS~▒U▒͗˫▒b▒▒98z}|▒▒x▒▒▒▒&i▒▒KJ▒▒▒▒▒b7П`U▒?1▒▒▒▒D▒
                                                                              ▒▒▒<kY▒&▒ۖ▒G▒jK▒_-X▒xf|▒▒▒▒▒/▒▒▒▒f?^P▒B▒▒&n>▒▒▒▒▒  ▒B0▒▒"'e▒▒▒▒▒<[▒=▒
G"rj)h+ݽ▒▒▒}▒q▒▒\▒▒▒▒▒u1O▒▒▒▒o6▒▒▒▒.▒▒▒▒▒▒ͣ=▒]▒{n▒
p{▒wW{▒^m▒߾▒|▒▒▒ۃk▒;▒ ▒▒        ▒▒▒,▒O▒▒▒G+▒▒▒▒'cE;<C?▒▒▒▒v▒▒ECf▒k▒a{Kش▒▒.:W--▒(▒▒▒▒▒>s▒p▒)p▒sP▒▒W▒0▒W▒▒[▒▒o▒H▒,Yh▒▒▒▒▒n▒\XrX▒e▒^       1▒T▒TV▒C▒▒▒C▒▒▒_{▒▒▒~▒C▒P͈+u▒▒▒ys<NgTlм▒)6mp▒w▒▒▒!▒^▒▒▒j▒▒▒ff:՚▒▒Z$▒▒VW[▒▒)▒]▒▒a۹▒▒▒▒n▒▒▒{O▒▒▒▒\▒▒k{▒rGF▒(?▒▒z▒▒9{F|▒E|▒'▒'▒▒▒H▒▒▒n
▒ǆ:▒▒$▒▒▒\4▒7▒▒▒▒r▒▒YC▒▒▒▒▒▒▒▒▒̚C
                                \▒!▒B#▒=▒@.ߒ▒F▒Ua▒z'▒▒.▒▒▒K▒n▒rbt▒i▒>▒_▒▒▒▒▒s▒▒g▒▒▒oBB▒՟?▒7W▒▒▒▒p▒1▒cq▒5{▒{▒e,▒X▒=&▒H▒!▒/vw▒▒c&▒▒k▒;▒▒▒q]▒▒ܙE▒|▒▒▒▒i▒tpt▒▒▒K▒鷏a▒zR▒.O▒T5▒▒▒@r7W▒▒8&▒\O_▒▒Iś▒▒L5M▒%M▒q▒▒▒▒▒^n▒▒.=:▒y}rtxtr▒wp\▒:▒▒▒▒▒p}▒▒I▒▒'▒IL]_=▒q[K▒▒▒R▒Bj▒▒hummingbird:willbigdata srlab$ PuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTY6cPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTY
-bash: PuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTY6cPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTYPuTTY:`

I then check the directory where I ran the curl command (/willbigdata) with `ls`, but it seems empty.

**Comment by kubu4** [comment]
Exit your connection to hummingbird.
Close PuTTY.
Open Git Bash and try connecting to hummingbird this way: $ssh srlab@humminbird's.IP.address
If this works, then try using your cURL command to download that file.

**Comment by sr320** [comment]
Pretty sure just forgot `-O`

The code is 

```
$ curl -O ftp://ftp.uniprot.org/pub/databases/uniprotcurrent_release/knowledgebase/complete/uniprot_sprot.fasta.gz
```

otherwise it just spits out garbage. (but you knew that)

**Comment by kubu4** [comment]
Yep, what Steven said.  Sorry for not catching that earlier.

Alternatively, you could also use the redirect symbol to rename the file when it downloads.  This will negate the need to use the "-O" flag.

Example:

```
$curl ftp://ftp.uniprot.org/pub/databases/uniprotcurrent_release/knowledgebase/complete/uniprot_sprot.fasta.gz > uniprot20150120.fasta.gz
```

**Comment by willking2** [comment]
Bingo. thanks
