### ISSUE TITLE
QC on raw reads

### ISSUE THREAD

**Issue by lisa418** [sr320/fish546-2015#18]
Hey Steven - I started running trinity on my 2 fastq files but as I was writing up the methods I realized I probably should have done some trimming beforehand re: removing adaptors, phred scores, read length. Is there an app in iplant you are using for this? Old QC manipulations were all done in CLC.

**Comment by kubu4** [comment]
I just realized I'm in the same boat.  I didn't run my raw data through any QC programs.

**Comment by sr320** [comment]
First thing to do is run through FastQC in IPlant.

**Comment by sr320** [comment]
See http://nbviewer.ipython.org/github/sr320/austral/blob/master/modules/01-Piura-Annotation/00_Piura.ipynb for example

**Comment by lisa418** [comment]
How long does the fastqc usually take? I started mine at 10am yesterday and it's still running. My 2 files are ~4GB each.

**Comment by kubu4** [comment]
Should be very fast; like < 30mins.

**Comment by lisa418** [comment]
Really? Grrrr! I'll kill it and try again I guess...

**Comment by kubu4** [comment]
I processed 6 files (~12GBs, total) on Hummingbird and it took < 40mins, so iPlant should (theoretically) be faster.

**Comment by lisa418** [comment]
I think there might be something wrong with my fastq files bc when I tried the fastqc again (both multi and single file) it FAILED. Then I tried to open the raw fastq files and my computer says not enough memory :-1: I'll be over after lunch for some hand holding :palm_tree:

**Comment by kubu4** [comment]
Update.  I'm running fastqc in iPlant on files that I trimmed (using fastx trimmer) and it's taking a LONG time.  Been going for about 2hrs now...

**Comment by kubu4** [comment]
Another update on my most recent FASTQC job:   It's still running, just like your was, Lisa.  That means it's been running for 18hrs now...

**Comment by sr320** [comment]
Something must be wrong...

—
Steven Roberts

**Comment by sr320** [comment]
So don't get too hung up with Fastqc this week - just get the workflows to completion and can easily switch in different data if structured correctly.
