### ISSUE TITLE
[quiz] What is the url for your github repository?

### ISSUE THREAD

**Issue by sr320** [sr320/fish546-2015#2]
Note you might have to think creatively how to integrate your daily research activity into the repository- Feel free to rely on the wiki feature.

**Comment by jldimond** [comment]
https://github.com/jldimond

**Comment by kubu4** [comment]
https://github.com/kubu4/fish546_2015

**Comment by lisa418** [comment]
https://github.com/lisa418/fish546-2015

**Comment by willking2** [comment]
https://github.com/willking2/fish546_W15

**Comment by sr320** [comment]
@jldimond that is not your repo url - thats your entire account.

**Comment by jldimond** [comment]
Oops, sorry...it is https://github.com/jldimond/fish546-2015

**Comment by jheare** [comment]
https://github.com/jheare/Fish546-Jake

I also included you as  a collaborator on the repository.
