### ISSUE TITLE
[quiz] Checksums

### ISSUE THREAD

**Issue by sr320** [sr320/fish546-2015#21]
What is a checksum algorithm?

**Comment by lisa418** [comment]
Important for checking data integrity and facilitating reproducibility. Helpful in keeping track of data versions because if your data changes so will the checksum. The two most common checksum algorithms are MD5 (most common) and SHA-1 (newer and preferred).

**Comment by kubu4** [comment]
A checksum algorithm examines a file's contents at the bit level and generates a "hash" value.  Because this hash is based off of a file's bit-content, a single alteration to any data of a file will result in a different hash value.

**Comment by jldimond** [comment]
Checksum algorithms detect changes in data, however small they may be. They can be used to check data integrity after file transfer or simply to see if any changes have been made.

**Comment by jheare** [comment]
Checksums are used to validate file integrity after it has been copied. If the checksum for the copy is the same as the original you can justifiably state that both files are identical. If the copy's checksum is different something may have changed during the duplication or move to another file system. This basically leaves a paper trail for data validation.

**Comment by willking2** [comment]
Checksum algorithm is basically a unique ID generated for a specific state of a particular file. Whenever the file is changed in any way, it gets a new ID (checksum). By using the shasum program (and others) in concert with the SHA-1 checksum, it is possible to validate multiple files at once. If the checksums are the same, the files are exactly the same.
