### ISSUE TITLE
[quiz] Completed workflow

### ISSUE THREAD

**Issue by sr320** [sr320/fish546-2015#22]
What is the url to your completed workflow? This can be in draft state but you need to a page where you go from start to finish. Does not have to be perfect and can even include Excel at this point....
If you need help recalling what you should be doing, see [this](https://github.com/sr320/fish546-2015/wiki/04_assignments).

**Comment by jheare** [comment]
I've created a Workflow for STACKS labeling the function, process, and output of every step. I've also included a basic guide for what everything does and why its important or why we chose certain options.  It includes a summary of the entire process at the end. It will be updated as I work on the data. 

You can see the workflow [here.](https://github.com/jheare/Fish546-Jake/blob/master/nb/RADSeqWorkflow.md)

**Comment by willking2** [comment]
https://github.com/willking2/fish546_W15/blob/master/nlap-ano/workflow.md

**Comment by sr320** [comment]
Please note this 'workflow' needs to be a document that someone else could use to replicate your work and get the same result.

Double Point Bonus :point_up_2: :heavy_multiplication_x:  :point_up_2:  for first one in..

**Comment by kubu4** [comment]
We discussed this quiz question in class and I think we're all confused on what exactly this means.  How does this differ from the methods.md we wrote?

**Comment by sr320** [comment]
So this should be markdown file, IPython nb, etc that documents
bioinformatic workflow in a manner which the work could be reproduced.

For example
http://nbviewer.ipython.org/github/sr320/eimd-sswd/blob/master/eimd_analysis.ipynb

Main point is showing steps how raw data is analyzed to get final product
(ie list of genes, annotated transciptome etc).

**Comment by jldimond** [comment]
http://nbviewer.ipython.org/github/jldimond/fish546-2015/blob/master/nb/CpG_ratio_graph_Ahya.ipynb

My progress on this was hampered by SQLshare not allowing me to download any of my datasets this afternoon. What is up with that?:thumbsdown:

**Comment by kubu4** [comment]
Whoa!  You have graphs! :+1: 

Any error message that you received from SQLShare regarding the downloads failing?

**Comment by sr320** [comment]
Related - show the error in your notebook so we can troubleshoot. 

In this case screenshots are handy.

You can also give us url directly to section in notebook.

—
Steven Roberts
