### ISSUE TITLE
Embed HTML (fastqc report) in IPython notebook?

### ISSUE THREAD

**Issue by kubu4** [sr320/fish546-2015#24]
I see that Jay managed to do this, but I can't seem to get it to work.  Could someone glance at my notebook (scroll to the bottom) and see if they have any thoughts on what I'm doing incorrectly?  I'd definitely appreciate it. I've even tried the full, absolute path for my HTML file, but I still get the "404 Not Found" error.

http://nbviewer.ipython.org/github/kubu4/fish546_2015/blob/master/Week02_FASTQC_local.ipynb

**Comment by sr320** [comment]
Try#embed fastqc report(s) in notebook
from IPython.display import HTML
HTML('<iframe src=./gigasHSrnaSeq/analysis/fastqc/2M_AGTCAA_L001_R1_001_fastqc.html width=100% height=650></iframe>')

—
Steven Roberts

**Comment by sr320** [comment]
Note it has to be relative...

—
Steven Roberts

**Comment by kubu4** [comment]
Dang, doesn't work.  I feel like I've tried every variation of the file path.

I also checked the permissions and the HTML file is readable.

One thing I'm noticing is that the colors of my "from IPython.display import HTML" don't match Jay's or other examples on the web (my IPython.display and HTML don't turn blue).  Wonder if that's an indicator of the potential problem?

**Comment by sr320** [comment]
**That file does not exist in your repo!!**

<img src="http://eagle.fish.washington.edu/cnidarian/skitch/fish546_2015_gigasHSrnaSeq_analysis_at_master_·_kubu4_fish546_2015_1A7985F8.png" alt="fish546_2015_gigasHSrnaSeq_analysis_at_master_·_kubu4_fish546_2015_1A7985F8.png"/>

**Comment by kubu4** [comment]
Thanks!  They're up there now.  Had the entire "analysis" folder in ignore file, due to large fastq, bed, bam files.

**Comment by sr320** [comment]
Note **solution** was ultimately that Ipython needed to be updated to render local html..

:beers:
