### ISSUE TITLE
uploading file to SQLshare from hummingbird

### ISSUE THREAD

**Issue by willking2** [sr320/fish546-2015#26]
In order to join tables on SQLShare, I want to first upload my blastx output (.tab) file to SQLshare. The .tab file is currently on Hummingbird.

I attempted to push my .tab file to github and get access to it that way, but can't figure out git's various error messages in Hummingbird command line (things aren't merged correctly, etc).

Is there another way to get that .tab file out of Hummingbird so that I can use it? If not, I will ask Steven for help with figuring out git tomorrow.

Thanks in advance

**Comment by sr320** [comment]
It always helps to provide url to notebook that shows errors for troubleshooting.

—
Steven Roberts

**Comment by sr320** [comment]
Also, at this stage, it's perfectly fine to sit down in front of hummingbird and work, transfer to usb etc.

—
Steven Roberts
