### ISSUE TITLE
markdown tips

### ISSUE THREAD

**Issue by sr320** [sr320/fish546-2015#27]
<img src="http://eagle.fish.washington.edu/cnidarian/skitch/README_md_1A7C4FE1.png" alt="README_md_1A7C4FE1.png"/>

**Comment by willking2** [comment]
~~Pro tip~~ Amateur tip for inserting images in `.md` for GitHub for PC users: PC local file path naturally has `\` slashes, but GitHub only likes `/`, so just manually change them in your `.md`. PC will still recognize it, and it'll work on GitHub.
