### ISSUE TITLE
[quiz] Visualize your end goal.

### ISSUE THREAD

**Issue by sr320** [sr320/fish546-2015#3]
What would you imagine as an ideal product from this course?

**Comment by lisa418** [comment]
black abalone transcriptome manuscript! #LFT :8ball: being realistic, I hope to at least have the methods and results solidified so I'm on track to bang out an intro and discussion after my re-exam at the beginning of spring.

**Comment by jldimond** [comment]
-A complete analysis of CpG ratio in coral 6 coral transcriptomes and associated env response datasets. Prediction (and data so far indicate) is that env response genes will show higher CpG ratios and hence lower levels of germline methylation.

-GOslim information associated with CpG ratios. Prediction is that genes with higher CpG ratios will be those with inducible functions

**Comment by willking2** [comment]
Comparison of _C. dalli_, _B. glandula_, and _S. caiosus_ transcriptomes that reveals a novel and interesting difference among the species. Analysis of possible stress response genes, heat shock protein?

**Comment by kubu4** [comment]
Gene expression comparison between heat shocked/non-heat shocked C.gigas tissue.  Possibly results comparison of different assemblers and/or expression analysis programs.

**Comment by jheare** [comment]
Working knowledge and code to process and analyze RAD-Seq data for future work. Also a stronger ability to use Git, ipython, and other programs to create version controlled notebooks.
