### ISSUE TITLE
CpG ratio and GOslim

### ISSUE THREAD

**Issue by jldimond** [sr320/fish546-2015#32]
Steven--In doing some analysis today it dawned on me that the transcriptome-wide CpG ratio analysis/plotting must be done independently from the analysis of CpG ratio according to GOslim terms. Joining the CpG file to the GOslim file duplicates CpG data for multiple GOslim terms, which is fine for the GOslim analysis but not for the transcriptome-wide analysis. So these files need to be analyzed separately. Maybe you already knew this, but I didn't!

**Comment by sr320** [comment]
I guess I am not following exactly - what do you mean by "transcriptome-wide CpG ratio analysis/plotting".

**Comment by jldimond** [comment]
Sorry-I am referring to the density plots of CpG ratio as the "transcriptome-wide" analysis. When plotting the density curves of CpG ratio in all the contigs, this should not come from a data file that has been joined to the annotation table. When joining (at least in SQLshare but also using bash I think) the CpG ratio table with the annotation table, contigs that fit into more than one GOslim bin are duplicated. We want that to happen for the analysis of CpG ratio in relation to GOslim bin (the bar graphs), because we don't want to arbitrarily constrain a contig to a single GOslim bin. But for the density curves, duplicated contigs can skew the distribution.
