### ISSUE TITLE
[tip] Running command on multiple files in directory

### ISSUE THREAD

**Issue by sr320** [sr320/fish546-2015#33]
in IPython the key is using the `%%bash` magic

here is an example

```
%%bash
for f in query.part*
do
blastx \
-query $f \
-db /usr/local/bioinformatics/dbs/uniprot_sprot.fasta \
-evalue 1e-5 \
-max_target_seqs 1 \
-max_hsps 1 \
-outfmt 6 \
-num_threads 16 \
-out blastout_"$f"_sprot
done
```

This takes the 5 'part' files below and will create 5 'blastout' files
<img src="http://eagle.fish.washington.edu/cnidarian/skitch/hummingbird_1A857DA1.png" alt="hummingbird_1A857DA1.png"/>

**Comment by kubu4** [comment]
I get a syntax error (at the %%bash) when I try this.  Is there anything else that needs to done prior to using the %%bash magics?

**Comment by kubu4** [comment]
Never mind.  Turns out when you employ the %%bash magics, it turns the <em>entire</em> cell into a shell.
I had a line I had commented out in the same cell and having that commented out was breaking the %%bash magics.

**Comment by kubu4** [comment]
To elaborate even further, the first line of the cell has to be the %%bash magics.  After that, comments are allowed.  Commenting the first line, followed by %%bash magics is what screws things up.
