### ISSUE TITLE
[quiz] Please list your primary data records.

### ISSUE THREAD

**Issue by sr320** [sr320/fish546-2015#34]
These are what you will be describing this week for you draft product.

**Comment by willking2** [comment]
- `N_lapillus.fa` - published _Nucella lapillus_ transcriptome
- `uniprot_sprot.fasta.gz` - Uniprot Swissprot dataset 
-  `SPID and GO Numbers` - Roberts lab table on SQLShare that connects SPID to GO
-  `GO_to_GOSlim` - Roberts lab table on SQLShare that connects GO to GOSlim
- `UniprotNamesNamesReviewed_yes20130610` - Roberts lab table on SQLShare that connects SPID to protein names

edited 2/8/15 17:09:
- `Nlap_uniprot_blastx.tab` - blastx output file (blast table)
- `Nlap_annotated_GO.csv` - contigs with GO, GOSlim (blast w/ complete GO info)
- `Nlap_annotated_proteinnames.csv` - contigs with protein functions (blast w/ protein names)

**Comment by sr320** [comment]
thanks @willking2 - just a reminder data records will also include what you create - ie 
- blast table
- blast table with protein names
- blast table with complete Gene Ontology information

**Comment by jheare** [comment]
You can view my primary data record [here](http://www.oldnavy.com/products/maternity-hats.jsp).

**Comment by sr320** [comment]
@jheare - note it asks for a **list**, not a link, and good luck listing these

<img src="http://eagle.fish.washington.edu/cnidarian/skitch/Maternity_Hats___Old_Navy_-_Free_Shipping_on__50_1A8D1BD8.png" alt="Maternity_Hats___Old_Navy_-_Free_Shipping_on__50_1A8D1BD8.png"/>

**Comment by jheare** [comment]
WHOOPS! Forgot to copy the address to my MD file. Don't ask why I was looking up maternity hats. Just don't. 

[Here](https://github.com/jheare/Fish546-Jake/blob/master/DATA_RECORDS.md) is the data record file which contains a list of the files used. There's a lot of files produced so I think the MD file might be easier than copying them all onto this section.

**Comment by jldimond** [comment]
| Input files | Description |
| --- | --- |
| 33496_Ahyacinthus_CoralContigs.fasta | _Acropora hyacinthus_ transcriptome |
| Ahya_diff_contigs | List of _A. hyacinthus_ differentially expressed contigs (temperature stress) |
| 33496_MasterCombinedAnnotationTablewHGNC.txt | _A. hyacinthus_ annotation table |
| SPID and GO Numbers | Table of SWISS-PROT and GO IDs |
| GO_to_GOSlim | Table of GO and GOSlim IDs |

| Output files | Description |
| --- | --- |
| ID_CpG.tab | File with contig ID and CpG ratio |
| Ahya_cpg_GOslim.csv | File resulting from joining of CpG ratio and GOSlim IDs |
| Ahya_diff_cpg_GOslim.csv | File resulting from joining of file above with only differentially expressed contigs |

**Comment by lisa418** [comment]
https://github.com/lisa418/fish546-2015/blob/master/draft/data_records.md

**Comment by kubu4** [comment]
I've listed all necessary/required files of my workflow, even though I'm sure many do not count as "primary" data records.

####Sequence Files
- 2M-HS_CCGTCC_L001_R1_001.fastq.gz
- 2M_AGTCAA_L001_R1_001.fastq.gz
- 4M-HS_GTCCGC_L001_R1_001.fastq.gz
- 4M_AGTTCC_L001_R1_001.fastq.gz
- 6M-HS_GTGAAA_L001_R1_001.fastq.gz
- 6M_ATGTCA_L001_R1_001.fastq.gz

####Genome File
- Crassostrea_gigas.GCA_000297895.1.24.dna_sm.genome.fa

####Genome Annotation File
- Crassostrea_gigas.GCA_000297895.1.24.gtf

####Pre-Trimming Quality Evaluation
- 2M-HS_CCGTCC_L001_R1_001.fastqc.html
- 2M_AGTCAA_L001_R1_001.fastqc.html
- 4M-HS_GTCCGC_L001_R1_001.fastqc.html
- 4M_AGTTCC_L001_R1_001.fastqc.html
- 6M-HS_GTGAAA_L001_R1_001.fastqc.html
- 6M_ATGTCA_L001_R1_001.fastqc.html

####Quality Trimming
- 2M-HS_CCGTCC_L001_R1_001.fastq.gz
- 2M_AGTCAA_L001_R1_001.fastq.gz
- 4M-HS_GTCCGC_L001_R1_001.fastq.gz
- 4M_AGTTCC_L001_R1_001.fastq.gz
- 6M-HS_GTGAAA_L001_R1_001.fastq.gz
- 6M_ATGTCA_L001_R1_001.fastq.gz

####Post-Trimming Quality Evaluation
- 2MHS_fastx_trimmed_fastqc.html
- 2M_fastx_trimmed_.fastqc.html
- 4MHS_fastx_trimmed_.fastqc.html
- 4M_fastx_trimmed_.fastqc.html
- 6MHS_fastx_trimmed_.fastqc.html
- 6M_fastx_trimmed_.fastqc.html

####Genome Index Files
- Crassostrea_gigas.GCA_000297895.1.24.dna_sm.genome.1.bt2  
- Crassostrea_gigas.GCA_000297895.1.24.dna_sm.genome.4.bt2
- Crassostrea_gigas.GCA_000297895.1.24.dna_sm.genome.2.bt2  
- Crassostrea_gigas.GCA_000297895.1.24.dna_sm.genome.rev.1.bt2
- Crassostrea_gigas.GCA_000297895.1.24.dna_sm.genome.3.bt2  
- Crassostrea_gigas.GCA_000297895.1.24.dna_sm.genome.rev.2.bt2

####Read Alignment Files (Pre- & Post-Heat shock each generate these files separately)
- accepted_hits.bam 
- deletions.bed  
- junctions.bed
- align_summary.txt
- insertions.bed
- unmapped.bam

####Transcriptome Assembly Files (Pre- & Post-Heat shock each generate these files separately)
- transcripts.gtf

####Transcriptome Merging (Pre- & Post-Heat shock each generate these files separately)
- merged.gtf

####Differential Expression
- cds.count_tracking
- genes.count_tracking
- isoforms.count_tracking
- tss_groups.count_tracking
- genes.fpkm_tracking
- isoforms.fpkm_tracking
- tss_groups.fpkm_tracking
- cds.fpkm_tracking
- genes.read_group_tracking
- tss_groups.read_group_tracking
- cds.read_group_tracking  
- isoforms.read_group_tracking
- isoform_exp.diff
- cds_exp.diff
- splicing.diff
- tss_group_exp.diff
- promoters.diff
- cds.diff
- gene_exp.diff
