### ISSUE TITLE
[quiz] What is the url for your draft product?

### ISSUE THREAD

**Issue by sr320** [sr320/fish546-2015#36]
See [this](https://github.com/sr320/fish546-2015/wiki/06_assignments) for instructions.

**Comment by willking2** [comment]
draft directory : https://github.com/willking2/fish546_W15/tree/master/nlap-ano/draft

**Comment by jldimond** [comment]
https://github.com/jldimond/fish546-2015/tree/master/Draft_product

**Comment by jheare** [comment]
[Product Draft Directory](https://github.com/jheare/Fish546-Jake/tree/master/Product%20Draft)

**Comment by kubu4** [comment]
https://github.com/kubu4/fish546_2015/tree/master/draft_product

**Comment by lisa418** [comment]
https://github.com/lisa418/fish546-2015/tree/master/draft

**Comment by kubu4** [comment]
Draft product updated.
