### ISSUE TITLE
How to refer to SQLShare tables in draft?

### ISSUE THREAD

**Issue by willking2** [sr320/fish546-2015#38]
Are there stable URLs for the SQLShare tables?

**Comment by sr320** [comment]
Yes, you can use URL when you open table. To be sure- post url here and we will try to open..

We can also get DOIs through SQLShare for proper citation

**Comment by willking2** [comment]
please try: 

https://sqlshare.escience.washington.edu/sqlshare/#s=query/wking2%40washington.edu/Nlap_annotated
