### ISSUE TITLE
Ostrea Lurida Reference Genome

### ISSUE THREAD

**Issue by seanb80** [sr320/fish546-2015#39]
I finished assembling my transcriptomes, and went to start blasting them and realized that I don't have a reference genome. Sam told me that  a working one exists, so I was wondering if there might be a way I could grab a link to it?

Thanks!
-Sean

**Comment by sr320** [comment]
I think what you want to do it blast transcriptome against Swiss-Prot UniProt in order to annotate?

**Comment by sr320** [comment]
See Piura Annotation Module 
http://nbviewer.ipython.org/github/sr320/austral/tree/master/modules/

**Comment by sr320** [comment]
Direct link
http://nbviewer.ipython.org/github/sr320/austral/blob/master/modules/01-Piura-Annotation/01-Local_BLAST.ipynb
