### ISSUE TITLE
[quiz] What software / computing approach are you most comfortable with?

### ISSUE THREAD

**Issue by sr320** [sr320/fish546-2015#4]

**Comment by jldimond** [comment]
In order of comfort starting with most:
R
iPython
SQLshare
bash/terminal
Git

**Comment by lisa418** [comment]
Comfortable with? None! SQLshare and Galaxy are pretty fun though :+1:

**Comment by willking2** [comment]
Can't claim to be comfortable with any computing approach except Excel. Some experience with R (simple graphs and stats). No experience with the other approaches that Jay listed.

**Comment by kubu4** [comment]
Comfortable with Git/Github.
Relatively comfortable with bash/IPython/SQLShare (i.e. can quickly figure out things I don't inherently know how to do).
Uncomfortable with R.

**Comment by jheare** [comment]
Most to least:
R
Python
Iplant
Git
Bash
SQLshare
Perl
