### ISSUE TITLE
Figure out how to html backup notebooks

### ISSUE THREAD

**Issue by sr320** [sr320/fish546-2015#40]

**Comment by kubu4** [comment]
Please post a URL to your file(s). :wink:

**Comment by sr320** [comment]
Nice- but actually looking for generic (automated) means to take ipynb files in a directory (and subdirectories) and write to server (i.e. owl) html files with time stamps in file names. Tried some stuff with Hazel with no luck.

**Comment by sr320** [comment]
Simple fix... 

<img src="http://eagle.fish.washington.edu/cnidarian/skitch/Hazel_1A90E660.png" alt="Hazel_1A90E660.png"/>

**Comment by sr320** [comment]
Could get a little more advance and also copy .html files to web server.
