### ISSUE TITLE
gunzip... has 1 other links -- skipping

### ISSUE THREAD

**Issue by closek** [sr320/fish546-2015#42]
I was able to unzip the files in batch, but three files were not unzipped and when trying to gunzip them separately I get the same error:

!gunzip -k 106A_Female_Mix_GATCAG_L007_R1_002.fastq.gz

gunzip: 106A_Female_Mix_GATCAG_L007_R1_002.fastq.gz has 1 other links -- skipping

Looking into it, but thought if someone else has come across this issue they might be able to provide a solution. Thanks.

**Comment by sr320** [comment]
Try to force it with `-f`

Do you need a fast version of that file?

**Comment by closek** [comment]
-f worked. Thanks!

I will need fasta files in the future.

**Comment by suharevA** [comment]
-f worked. Thanks!
