### ISSUE TITLE
Ignore files >100MB in your Git repos 

### ISSUE THREAD

**Issue by sr320** [sr320/fish546-2015#43]
via @kubu4 

Easiest way I've found to ignore those large files is the following:

In the shell:
1. Change to your Git repo directory
2. `find ./* -size +100M | cat >> .gitignore`

The command explained:

Find all files in my current directory, and all those directories contained within, that are >100MB.  Concatenate this list to the .gitignore file.﻿

**Comment by shivam13juna** [comment]
We need to remove the "./" then, .gitignore works, this command does that. 

 find . -size +1G | sed 's|^\./||g' | cat >> .gitignore

**Comment by petre-c** [comment]
The command above will add large file paths to `.gitignore`, even if they're already present in the file.

Below script will add files larger than 10M to `.gitignore` and then remove duplicate entries from it:

```sh
find . -size +10M | sed 's|^./||g' | cat >> .gitignore
sort .gitignore | uniq  > temp_file && mv temp_file .gitignore
```
