### ISSUE TITLE
Why won't sqlshare-python client work for me?

### ISSUE THREAD

**Issue by jldimond** [sr320/fish546-2015#46]
Anyone know why I might be getting this error message? I followed all the install instructions but can't seem to get this to work.

![untitled2](https://cloud.githubusercontent.com/assets/9869457/6192791/6dcd1a92-b36a-11e4-98f0-e05a0c53eb8e.png)

**Comment by sr320** [comment]
my first guess is the install of the config file. This normally trips people up.
1. Make sure your own API key is configured in your home directory, in the file `.sqlshare/config`.
   
   On Mac or Linux platforms, you can create the directory: `mkdir -p ~/.sqlshare`.
   
   Then create a file called `config` in that directory using your favorite editor (e.g., `vim ~/.sqlshare/config`) with the following contents:
   
   ```
   [sqlshare]
   user=your-sql-share-account-name
   password=your-sql-share-account-key
   ```

---

what do you get if you just run the first line in command line ? (sans `!`)

**Comment by sr320** [comment]
Also what are the contents and path of your `config` file?

**Comment by jldimond** [comment]
/home/jay/sqlshare-pythonclient/config

contents:

[sqlshare]
user=jldimond@washington.edu
password=4da436d9f857fdf0fd120688356a5d95

**Comment by jldimond** [comment]
I get the same message if I run:

jay@jay-UL30A:~$ python /home/jay/sqlshare-pythonclient/tools/singleupload.py
Traceback (most recent call last):
  File "/home/jay/sqlshare-pythonclient/tools/singleupload.py", line 6, in <module>
    import sqlshare
ImportError: No module named sqlshare

**Comment by sr320** [comment]
So... 

the location on `config` file is the issue. 

it needs to be `~/.sqlshare/config`. see comment above.

**Comment by sr320** [comment]
To verify the config file is in the correct location, you should be able to type the following at command line

$ `cd`
$ `ls .sqlshare`
output will be `config`

**Comment by jldimond** [comment]
OK...but, when I did this:

mkdir -p ~/.sqlshare
nano ~/.sqlshare/config

It showed that I had already made the config file, with all the right contents.

**Comment by jldimond** [comment]
jay@jay-UL30A:~$ ls .sqlshare
config

**Comment by sr320** [comment]
well then your path above `/home/jay/sqlshare-pythonclient/config` was not accurate?
That was the basis for my assumption.

**Comment by jldimond** [comment]
I apparently have the config file in both places

**Comment by sr320** [comment]
Nothing then. Restart computer, cross fingers. We can try going through install Tuesday. What operating system? Linux?

**Comment by sr320** [comment]
The error is that python libraries are not installed.
This would suggest 
`python setup.py install` did not work. Did you get any errors when you did this?

**Comment by jldimond** [comment]
I'm using Linux-Ubuntu. And I've been trying this from time to time for several weeks.
No errors, seems to work fine:

jay@jay-UL30A:~/Downloads/sqlshare-pythonclient-master$ sudo python setup.py install
[sudo] password for jay: 
running install
running bdist_egg
running egg_info
writing SQLShare.egg-info/PKG-INFO
writing top-level names to SQLShare.egg-info/top_level.txt
writing dependency_links to SQLShare.egg-info/dependency_links.txt
reading manifest file 'SQLShare.egg-info/SOURCES.txt'
writing manifest file 'SQLShare.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/sqlshare
copying build/lib.linux-x86_64-2.7/sqlshare/**init**.py -> build/bdist.linux-x86_64/egg/sqlshare
byte-compiling build/bdist.linux-x86_64/egg/sqlshare/**init**.py to **init**.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying SQLShare.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying SQLShare.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying SQLShare.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying SQLShare.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/SQLShare-0.1a-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing SQLShare-0.1a-py2.7.egg
Removing /usr/local/lib/python2.7/dist-packages/SQLShare-0.1a-py2.7.egg
Copying SQLShare-0.1a-py2.7.egg to /usr/local/lib/python2.7/dist-packages
SQLShare 0.1a is already the active version in easy-install.pth

Installed /usr/local/lib/python2.7/dist-packages/SQLShare-0.1a-py2.7.egg
Processing dependencies for SQLShare==0.1a
Finished processing dependencies for SQLShare==0.1a

**Comment by sr320** [comment]
You can also submit issue to escience

https://github.com/uwescience/sqlshare-pythonclient/issues

maybe in issue show them the install code. and tell them the error you are
getting.

Steven Roberts

**Comment by kubu4** [comment]
@jldimond, looks like Mac had the [same problem at some point](https://github.com/uwescience/sqlshare-pythonclient/issues/2) .  After she updates to a newer version of Python, she gets the error message you got. However, it's not entirely clear to me what the actual resolution was.  I'll try to install the SQLShare API on Ubuntu and see if I encounter the same problem.

**Comment by sr320** [comment]
@jldimond any resolution?

**Comment by jldimond** [comment]
@kubu4 was kind enough to make sure I had properly downloaded the software and we tried some commands...but still no dice. I'll try posting the issue to the folks over at SQLShare.

**Comment by kubu4** [comment]
@jldimond, be sure to show them the output of your `$which python`. I think that will help. I have a feeling that this is the source of the issue.

**Comment by kubu4** [comment]
To clarify on why I think `$which python` will be helpful, from what we saw yesterday, your system is using the Python installed by/with the Anaconda software by default.  

But, looking at your install output above, SQLShare is installing with your Linux system's built-in Python (e.g. `Installed /usr/local/lib/python2.7/dist-packages/SQLShare-0.1a-py2.7.egg`).

Doing some looking around, it seems that this might be able to be alleviated by changing the order that the Anaconda version of Python appears in your system path.  I'm guessing what's happening is, as the system loads and goes through the various system paths to identify software to use for various tasks, it encounters the Anaconda Python when it looks for Python.  Once it finds Anaconda Python, it stops looking through the rest of the paths because it doesn't need to look any further to find software to run Python modules. So, if you can re-order your system path to have the default Python come before the Anaconda Python, you'll be good to go.

However, shoot the issue to the SQLShare people and hopefully they'll have a nice, concise explanation of how to make that change.

**Comment by jldimond** [comment]
Thanks--I'll mention that. This is on my to do list for tomorrow.
