### ISSUE TITLE
Joining files using bash, and problems with tabs

### ISSUE THREAD

**Issue by jldimond** [sr320/fish546-2015#47]
Steven, I've tried replicating your code as shown here:

http://nbviewer.ipython.org/github/sr320/fish546-2015/blob/master/notebooks/Jay-CpG.ipynb#Join-with-GO-Slim

But when I try to join, it says:

join: multi-character tab ‘$\t’

Any ideas?

**Comment by sr320** [comment]
put in url to your notebook so I can see and access files.

this might help
http://blog.52nlp.org/error-join-multi-character-tab-t-for-using-join-tab/comment-page-1/

**Comment by jldimond** [comment]
http://nbviewer.ipython.org/github/jldimond/fish546-2015/blob/master/nb/CpG_ratio_graph_Ahya2.ipynb#Now-joining-CpG-to-GOslim,-but-first-must-sort-files.

**Comment by sr320** [comment]
Are the files you are trying to join in GitHub- I could not find them..

Steven Roberts

**Comment by jldimond** [comment]
Sorry, I will get them in there...

**Comment by jldimond** [comment]
OK I pushed everything up there

**Comment by jldimond** [comment]
I tried variations on what was shown in the blog above, but did not work

**Comment by sr320** [comment]
File format (Line Breaks)

GOSlim was Windows - needs to be Unix

<img src="http://eagle.fish.washington.edu/cnidarian/skitch/Save_and_Ahya_GOSlim_sorted_1A8E915D.png" alt="Save_and_Ahya_GOSlim_sorted_1A8E915D.png"/>

After I saved as Unix in TextWrangler

<img src="http://eagle.fish.washington.edu/cnidarian/skitch/Jay-join_1A8E91AC.png" alt="Jay-join_1A8E91AC.png"/>

**Comment by jldimond** [comment]
Ok thanks - I will try this later...have to go to work.

**Comment by jldimond** [comment]
I was able to do what you did, but it results in a file that is not tab delimited and I can't figure out how to make it tab delimited. I tried inserting tabs:

!awk -F $'\t' '{print $1, "\t", $2, "\t", $3}'

But that just puts two new columns at the end.

**Comment by jldimond** [comment]
I did find a Linux command that can be used to do what you did manually in Text Wrangler...

[dos2unix](http://linuxcommand.org/man_pages/dos2unix1.html)

**Comment by jldimond** [comment]
Whew, figured it out! Not pretty but it works. I converted the file with spaces to tabs, then inserted a space instead of a tab between the two words in the GO slim bin. I'm sure there's a way to cut out a step, but for now it is working.

I should also mention that I somehow managed to overwrite my original iPython notebook, so some of what I have written in my draft product will pertain to the analysis in the original notebook. I am in the process of converting most of the join operations to bash instead of SQLshare.

**Comment by sr320** [comment]
Good
Based on my example notebook this should have done it
`!awk -F $'\t' '{print $1, "\t", $2}' ../analyses/Ahyacinthus_GOslim.sorted > ../analyses/Ahyacinthus_GOslim.sortedtab`

<img src="http://eagle.fish.washington.edu/cnidarian/skitch/Jay-join_1A8EEEBF.png" alt="Jay-join_1A8EEEBF.png"/>
