### ISSUE TITLE
nbviewer cannot display notebooks >25MB

### ISSUE THREAD

**Issue by kubu4** [sr320/fish546-2015#48]
The 503 error that keeps popping up on most of my notebooks is caused by the fact that they are larger than 25MB.  Apparently, this is due to a limitation imposed on nbviewer by the Github API:

https://github.com/jupyter/nbviewer/issues/408#issuecomment-74274722

**Comment by sr320** [comment]
Interesting- did not know that. Why are notebooks getting that big? Std error? Note I did use '2>' on BSMAP today successfully - will try on blast next.

**Comment by kubu4** [comment]
I think stdout, primarily from Cufflinks. However, I haven't had time to determine if stderror is also involved.

**Comment by sr320** [comment]
works with blast - I will probably just start doing this if not for just better organization alone

<img src="http://eagle.fish.washington.edu/cnidarian/skitch/hummingbird_1A93FC67.png" alt="hummingbird_1A93FC67.png"/>

**Comment by kubu4** [comment]
Very nice! Will have to give this a go with Cufflinks...

**Comment by kubu4** [comment]
This worked perfectly with Cufflinks. Now, my notebook is actually viewable with nbviewer again!  Thanks!
