### ISSUE TITLE
[quiz] Next Image

### ISSUE THREAD

**Issue by sr320** [sr320/fish546-2015#49]
Last week you completed a product where you described your efforts and results. 
Describe in words what you think a good visual representation of these results would be.

**Comment by willking2** [comment]
- bar graph of protein function by frequency
- pie chart of proportions of contigs devoted to general protein functions 

do visualizations for whole transcriptome and stress related subset

**Comment by jldimond** [comment]
The comparison of CpG ratio between deferentially expressed contigs and the whole transcriptome is key for my study. For each species I hope to have density plots showing this comparison, as well as bar graphs showing mean CpG ratio for each GO term. I also want to think about ways to graphically (or perhaps show in a table) summarize the data across species, such as ranking CpG ratio by GO term and comparing these ranks between species.

**Comment by lisa418** [comment]
Visualizations I would like to include:
DEG table
MA plot (R)
semantic similarity-based scatter-plot (REViGO)

**Comment by jheare** [comment]
Working SQL interface with the data set. It should provide visual information for each sample and comparisons to the other samples.

**Comment by kubu4** [comment]
- Heat map(s) of differentially expressed genes, binned by GO/GO Slim.
- Pie charts showing differences in percentages of GO/GO Slim terms comprising control and experimental groups.
- REVIGO plots
