### ISSUE TITLE
[quiz] What is one thing...

### ISSUE THREAD

**Issue by sr320** [sr320/fish546-2015#51]
Have a look at everyone else's draft product. 
(see https://github.com/sr320/fish546-2015/issues/36)

For each one, list something you think they did a good job with.

**Comment by kubu4** [comment]
Will - Great organization (including use of README file). Very clear and concise.

Jay - Sweet background section!  Practically ready for publication!

Jake - I like your data record file. It's great that you list the file locations within your project's directories.

Lisa - Good concise background. Nice that you have README file for project.

**Comment by willking2** [comment]
Jay :joy_cat: 
Good background/intro. Your data record tables are clear and helpful. 

Jake :jack_o_lantern: 
You did a good job describing the numerous components of your methods and linking to your ipython notebooks. 

Lisa :lollipop:
Nice job putting your study in context of abalone disease and describing relevance to conservation. 

Sam :snowflake: 
Sweet data records file. Well organized and thorough.

**Comment by lisa418** [comment]
Will - Super organized and concise making it easy for others to follow.
Jay - Awesome background! I like your input/output tables in your data records section too. 
Jake - Nice methods with links to notebook. 
Sam - Methods are clear and easy to follow. Good detail in the data records section.

**Comment by jldimond** [comment]
**Will** - Data records file is very detailed and well organized.
**Jake** - Background and methods are very detailed with good use of links.
**Sam** - You've got a lot of steps but your methods section breaks it down nicely and is very approachable.
**Lisa** - I think you're the only one of us with a title! And I like your use of links in the data records section.

**Comment by jheare** [comment]
**Will** - Your formatting is very easy on the eyes. Flows well with your organization. 
**Jay** - Your background is very detailed and thorough. Definitely looks manuscript ready. 
**Sam** - Excellent work on providing details of your digital workspace. 
**Lisa** - Good clear explanations in the data record section.
