### ISSUE TITLE
Extracting useful data from supplementary files

### ISSUE THREAD

**Issue by jldimond** [sr320/fish546-2015#52]
There are several instances where I'd like to be able to perform an analysis on some genes/contigs that were differentially expressed in response to something. But often, all the authors provide is a supplementary file with a list of ambiguous IDs or Uniprot/Swissprot matches. [Here's an example](http://onlinelibrary.wiley.com.offcampus.lib.washington.edu/store/10.1111/gcb.12592/asset/supinfo/gcb12592-sup-0001-SupportingInformation.docx?v=1&s=c9a2d3ef0adfb573a268323547a514b32fa0186d)(scroll down to Table S1 on page 7). In this example, some of the genes have Swissprot matches. Can I use the Swissprot IDs to get FASTA sequences to do CpG ratio analysis on, or would that be considered improper given that the Swissprot ID is only a best match and not necessarily the actual sequence?

**Comment by sr320** [comment]
Do the ambiguous ID'S match their contig id's?

—
Steven Roberts

**Comment by jldimond** [comment]
Nope--I've been able to get a lot of data that way, but in some cases, particularly with the microarray datasets, the ID numbers seem useless in terms of getting to an actual sequence.

**Comment by sr320** [comment]
Email correspondening author 

—
Steven Roberts

**Comment by jldimond** [comment]
OK

**Comment by sr320** [comment]
Here are the sequences (probes) and corresponding IDs.

http://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?view=data&acc=GPL17270&id=9619&db=GeoDb_blob99

This is an array - persons have submit raw data for array at NCBI - the accession number is in Supp file.

**Comment by jldimond** [comment]
I had seen these supplementary files before, but I thought you couldn't really do anything meaningful with the probe sequences since they are only 60 nucleotides long (granted, they are long enough to hybridize with the sequence of interest). So you think it's OK to do CpG analysis on these probe sequences? 

Another thing about microarrays is that my understanding is that the probes are chosen in advance and so it's not really a "randomized" process like RNAseq. So from that standpoint, does it make analyzing CpG ratio in array data different from RNAseq data, where you have a much more random sample? Maybe I'm totally wrong--just my impression.

**Comment by sr320** [comment]
All very good points.

I would start with analyzing all transcriptomes first, before delving into
DEGs of any type. Once that is done- lets look at that- and then decide how
to approach DEGs

Steven Roberts

**Comment by jldimond** [comment]
Sounds like a good plan, I'll focus on the transcriptomes for now.
