### ISSUE TITLE
[quiz] What is the url to your workflow.

### ISSUE THREAD

**Issue by sr320** [sr320/fish546-2015#54]
See - https://github.com/sr320/fish546-2015/wiki/08_assignments - for details.

**Comment by willking2** [comment]
https://github.com/willking2/fish546_W15/blob/master/nlap-ano/workflow.md

(revisions will be ongoing until Friday 2pm)

**Comment by jldimond** [comment]
http://nbviewer.ipython.org/github/jldimond/fish546-2015/tree/master/nb/

This will link to all iPython notebooks. The only analysis that is complete at this point is _A. hyacinthus_. The others are in progress.

**Comment by jheare** [comment]
Workflow [here](https://github.com/jheare/Fish546-Jake/blob/master/nb/RSworkflow2.md). The workflow is a md file with links to pertinent ipython notebooks to show how each step was performed with exact commands used.

**Comment by kubu4** [comment]
http://nbviewer.ipython.org/github/kubu4/fish546_2015/blob/master/RNAseq_TopHat_Cufflinks_Workflow.ipynb
