### ISSUE TITLE
[quiz] What is the most profound new biological information you have learned to date.

### ISSUE THREAD

**Issue by sr320** [sr320/fish546-2015#55]
This refers to what your results indicate.

**Comment by willking2** [comment]
For an organism living in such a stressful environment, only about 2% of the transcriptome of _Nucella lapillus_ is related to stress response (plots and percentages [here](https://github.com/willking2/fish546_W15/blob/master/nlap-ano/analyses/Nlap_GO_plot.xlsx)). Although, a few transcribed sequences might still have a big effect..

**Comment by jldimond** [comment]
Most transcriptomes exhibit the familiar bimodal CpG ratio pattern, suggesting somewhat distinct groups of hyper- and hypomethylated genes. However, the coral transcriptomes seem to show larger groups of hypomethylated genes than in _C. gigas_. Shown below is the CpG ratio density plot for _Acropora hyacinthus_.

![index](https://cloud.githubusercontent.com/assets/9869457/6405361/7340bcdc-bdd7-11e4-879a-894fe9b0a8ef.png)

**Comment by jheare** [comment]
I haven't produce anything profound but I have learned there is definitely some SNP variation among O.lurida individuals which I think will help in the future with identifying genotypes and what not for each population.

**Comment by kubu4** [comment]
I still haven't gotten beyond the cuffdiff output to assess biological information. Additionally, I noticed a critical error in my workflow and had to re-run most of it earlier this week.

**Comment by jldimond** [comment]
@willking2 - I was just reading a paper that corroborates your finding of only 2% of genes being related to stress response in _Nucella_. See Fig. 2 of this paper:

http://onlinelibrary.wiley.com/doi/10.1111/1755-0998.12383/full

Looks like about 3-4% of genes fell in the stress response category.
