### ISSUE TITLE
[quiz] What is the most profound new technical information you have learned to date.

### ISSUE THREAD

**Issue by sr320** [sr320/fish546-2015#56]
This refers to a new bioinformatic skill you have learned to date.

**Comment by willking2** [comment]
`Git` is the best skill I've learned so far. I'm going to use it for version control in my future projects, bioinformatics or otherwise.

**Comment by jldimond** [comment]
Where to start---SQLshare, iPython, Git, bash, etc. But most of these tools would be useless without some knowledge of bash. I'm slowly starting to get adventurous with commands like `sed` and `awk`.

**Comment by jheare** [comment]
How to actually run STACKS and get information out of it. I'm still finagling the finer points but just being able to produce something is beneficial.

**Comment by kubu4** [comment]
Better grasp of using for loops and using commands to manipulate file names in bash.
