### ISSUE TITLE
[quiz] Can someone replicate your results with only having access to your Workflow?

### ISSUE THREAD

**Issue by sr320** [sr320/fish546-2015#58]

**Comment by jldimond** [comment]
I think so, or at least I'm getting there.

**Comment by jheare** [comment]
With a few minor changes to file directories and what not, they could easily replicate my work.

**Comment by kubu4** [comment]
Yes.

**Comment by willking2** [comment]
yes

**Comment by kubu4** [comment]
Changed my answer. Nope, no one can currently replicate my work, not even me. :angry:

**Comment by kubu4** [comment]
Fixed! Someone can replicate my work (again)! :smile:
