### ISSUE TITLE
[quiz] File Test

### ISSUE THREAD

**Issue by sr320** [sr320/fish546-2015#59]
What file in your repo would you say someone would have to generate (and be the same as yours) to ensure they replicated your workflow accurately?

**Comment by willking2** [comment]
I would be confident that someone replicated my workflow accurately if they can reproduce my stress response subset of the _Nucella lapillus_ transcriptome annotated with protein names file ([`Nlap_annotated_proteinnames_stress.csv`](https://github.com/willking2/fish546_W15/blob/master/nlap-ano/products/Nlap_annotated_proteinnames_stress.csv)). This file is near the end of my workflow and depends on numerous steps before it.

**Comment by jheare** [comment]
All the files produced by the sstacks function as they require all the previous steps to function appropriately before they can be generated.

**Comment by jldimond** [comment]
I have two primary output files for each species that would need to be replicated. One is called `ID_CpG.tab` and the other is `{species_name}_cpg_GOslim.tab2`

**Comment by kubu4** [comment]
My workflow is "automated" and uses the same input files. As long as the input files (reference genome files, Illumina FASTQ files) aren't altered, the output of my workflow will be replicated exactly.
