### ISSUE TITLE
[quiz] Course_Project

### ISSUE THREAD

**Issue by sr320** [sr320/fish546-2015#60]
What is the url for your `Course_Project` directory - see [this](https://github.com/sr320/fish546-2015/wiki/09_assignments) for details.

**Comment by willking2** [comment]
https://github.com/willking2/fish546_W15/tree/master/nlap-ano/Course_Project
(revisions ongoing)

**Comment by jheare** [comment]
My Course Project directory can be found [here](https://github.com/jheare/Fish546-Jake/tree/master/Course%20Project).

**Comment by jldimond** [comment]
https://github.com/jldimond/fish546-2015/tree/master/Course_Project

**Comment by kubu4** [comment]
https://github.com/kubu4/fish546_2015/tree/master/Course_Project

**Comment by sr320** [comment]
@kubu4 missing a bit?

**Comment by kubu4** [comment]
Ha! Haven't copied/moved stuff over. Trying out Git branching to work with some of the files.

And, technically, you only asked for the URL to our directory... :wink:
