### ISSUE TITLE
Cannot set working directory in iPython notebook

### ISSUE THREAD

**Issue by jldimond** [sr320/fish546-2015#61]
For some reason, I can't set my working directory in iPython notebook. It will not change from the directory in which the notebook itself is located. Anyone have any ideas why this might be?

![untitled3](https://cloud.githubusercontent.com/assets/9869457/6514158/207504dc-c335-11e4-80f2-0b9503d6fac7.png)

**Comment by sr320** [comment]
Get rid of ! And comment 

—
Steven Roberts

**Comment by jldimond** [comment]
I see--I put in the comments, and then it seemed like it wanted a ! in order to work. Thank you.
