### ISSUE TITLE
Turn 100bp SE data to 33,33,34 bp data

### ISSUE THREAD

**Issue by sr320** [sr320/fish546-2015#62]
How can I take a 100bp run and chop up reads?

i.e. lets say its fasta format

```
>read-000001
agcatgactagctagcgcatatgctatagctagcatcgtacggatcgatcgatcgatcgatcgatcgacgatcga
```

to 

```
>read-000001-a
agcatgactagctagcgcata
>read-000001-b
tgctatagctagcatcgtacgatcgatc
>read-000001-c
gatcgatcgatccgatcgacgatcga
```

**Comment by kubu4** [comment]
Haven't looked too hard yet, but the [FASTX-Toolki](http://hannonlab.cshl.edu/fastx_toolkit/commandline.html) has a FASTA splitter that allows you to specify min/max line lengths (i.e. sequence lengths). However, it doesn't allow for making a new FASTA identity line for each new line.

Regardless, I think it will get very tricky trying to accomplish this task on a multi-FASTA file (which I'm assuming you have)...

Might need Giles for this one!

**Comment by kubu4** [comment]
I think this will actually require a script that uses a combination of variables, for loops, if statements and sed.

In my mind, I see the script as something like this:
1. Use FASTA splitter in FASTX toolkit to break sequences into desired lengths.
2. For each line in that file...

2a. If the line begins with ">", save that line in a variable

2b. else, insert new line

2c. count new line

2d. replace new line with contents of variable, append with value from counter (in 2c)

**Comment by kubu4** [comment]
Looks like there are a few choices to accomplish your original task here: https://www.biostars.org/p/57911/
