### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by closek** [sr320/fish546-2015#64]
Is this due to space limitation on the server or Volumes/Data? (see error output below)

!time /usr/local/bioinformatics/fastx_toolkit-0.0.13.2/bin/fastx_trimmer -Q33 -f 15 -z \
-i /Volumes/Data/Collin/O_lurida_OA/rawdata/filtered_106A_Male_Mix_TAGCTT_L004_R1.fastq \
-o /Volumes/Data/Collin/O_lurida_OA/rawdata/filtered_106A_Male_Mix_TAGCTT_L004_R1_trimmed.fastq.gz

gzip: write: No space left on device
fastx_trimmer: writing sequence identifier failed: Broken pipe

**Comment by closek** [comment]
seems like it:

![screen shot 2015-03-06 at 4 17 48 pm](https://cloud.githubusercontent.com/assets/8381026/6538842/6222e1fa-c41c-11e4-9231-e76435f82e98.png)

**Comment by sr320** [comment]
Yep - maybe write to eagle?

Try /Volumes/web/scaphapoda

—
Steven Roberts

**Comment by closek** [comment]
Yep, will do. Thanks.

**Comment by closek** [comment]
mkdir: /Volumes/Eagle/Collin: Permission denied

**Comment by closek** [comment]
Can you give me permission or create a new directory that I could write to?  Thanks in advance.

**Comment by sr320** [comment]
Maybe try 

Volumes/web/scaphapoda

—
Steven Roberts

**Comment by sr320** [comment]
And who are you on hummimgbird? srlab ?

—
Steven Roberts

**Comment by kubu4** [comment]
I just cleared up 50GB of space on Hummingbird. To see which folders are using space:

Change to the /Volumes/Data directory and then run:

`$du -hscx *`

The 50GB I cleared was being used by my git repo in "hidden" files and whatnot. Still have to figure out how to clean it up further.

**Comment by sr320** [comment]
Thanks- could also buy more disks

—
Steven Roberts

**Comment by kubu4** [comment]
I freed up space in my git repo by running the following command (READ FULL POST BEFORE EXECUTING!):

`$git clean -d -x -f`

You can (and should) replace the -f flag with the -n flag first. This will perform a "dry run" and will show you what is going to be removed. Once you're confident that nothing critical will be removed, then run the command with the -f flag.

**Comment by kubu4** [comment]
@sr320 true, but that takes time. Plus, I think poor understanding/use of git is unnecessarily eating up space. That's certainly the case for my repo...

**Comment by closek** [comment]
@sr320 srlab
Thanks Sam. Cleaning up left 5% available in /Volumes/Data. 
![screen shot 2015-03-06 at 5 19 14 pm](https://cloud.githubusercontent.com/assets/8381026/6539278/f99fa3e4-c424-11e4-9b92-664d0f04da13.png)

I'm clearly using up more space than others

**Comment by closek** [comment]
hummingbird:Volumes srlab$ cd /Volumes/web/scaphapoda
-bash: cd: /Volumes/web/scaphapoda: Permission denied

**Comment by kubu4** [comment]
@closek you have to mount the drive yourself. @sr320 mounted /Volumes/web, so he's the owner (meaning you won't be able to access it).

You can find out how to mount a remote drive in @sr320/LabDocs/code repo.

**Comment by kubu4** [comment]
IP address for Eagle is: 128.95.149.81

**Comment by jheare** [comment]
You might want to delete that. Being public and all.

**Comment by sr320** [comment]
IP Is fine to be public 

—
Steven Roberts

**Comment by sr320** [comment]
@closek I mounted for you - /Volumes/web-1/scaphapoda 

Should work now

—
Steven Roberts

**Comment by kubu4** [comment]
@sr320 weird, getting permission denied (when trying to change directories to web-1) on that...

**Comment by sr320** [comment]
Odd - I am on hummimgbird now - screenshare- and worked as srlab 

—
Steven Roberts

**Comment by closek** [comment]
running. Thanks @sr320 & @kubu4!

**Comment by sr320** [comment]
#winningnotwinning

—
Steven Roberts

**Comment by kubu4** [comment]
Duh, my bad. I was using as my user account and not srlab.

**Comment by kubu4** [comment]
I freed up anothe 60GBs of space in my git repo by running the following commands in my git repo:
1. `$git count-objects -vH`
   This command will show you how much space your git repo is using, particularly the "git garbage"
2. `$git repack -Adf`
   This command does some sort of repacking of the git files. Don't know exactly what, but it seems to re-evaluate the compression being used and reorganize the files to be more efficiently compressed. May require the use of `sudo`.
3. `$git prune`
   This command cleans up and "loose' garbage files.
