### ISSUE TITLE
[quiz] FigShare / Extra Credit / Survey

### ISSUE THREAD

**Issue by sr320** [sr320/fish546-2015#65]
Reminder your FigShare product needs to be published and public url posted here, by Friday 2pm to get full credit (20% of final grade). I will be in FTR 230 tomorrow to answer any questions and provide technical help. 

**Extra Credit?** If you are interested in (or in need of) extra credit, you can reproduce someone else's work and show how you did it. This is due (posting url here) by Sunday 2pm. 

And finally, please fill out the course survey @ https://uw.iasystem.org/survey/139933

**Comment by jheare** [comment]
[Here](http://dx.doi.org/10.6084/m9.figshare.1336051) is the Figshare version of the project. I may update it this week but this version currently works for me.

**Comment by willking2** [comment]
URL: http://figshare.com/articles/Nucella_lapillus_transcriptome_annotation/1337937

**Comment by jldimond** [comment]
http://figshare.com/articles/Germline_methylation_of_five_coral_transcriptomes/1342817

**Comment by kubu4** [comment]
http://figshare.com/articles/Gene_expression_analysis_of_Pacific_oysters_Crassostrea_gigas_subjected_to_accute_heat_stress/1344541

**Comment by sr320** [comment]
:wave: :microphone:
