### ISSUE TITLE
ipython notebook setup

### ISSUE THREAD

**Issue by lisa418** [sr320/fish546-2015#7]
Ugh! I can never get this to work! I downloaded the Anaconda Python distribution installer and saved files to my home directory but when I open terminal and execute the following: 
Lisa-MacBook-Pro:~ friedmanlab$ bash Anaconda-2.1.0-MacOSX-x86_64.sh
this is what I get:
bash: Anaconda-2.1.0-MacOSX-x86_64.sh: No such file or directory

Am I missing a step or doing something wrong? Is there an easier way to launch this?

**Comment by sr320** [comment]
Yes, Yes,
Just do a plain markdown file for now, come by at 3pm and I can help you set up IPython

**Comment by kubu4** [comment]
Just saw this.  Quick description of the solution?
