### ISSUE TITLE
[quiz] What caused different differential expression result?

### ISSUE THREAD

**Issue by sr320** [sr320/fish546-2015#8]
In last weeks reading the author talks about an unusual event where results of differential gene expression analysis was dramatically different than a prior analysis. What was determined to be the cause of this?  
What lesson does this teach you?

**Comment by willking2** [comment]
Cause: turns out it was due to a change in the version of the R package. 
Lesson: metadata should be detailed enough to include things like software version, and person reading metadata should be aware of these possible discrepancies

**Comment by jheare** [comment]
R had been updated after the initial run of the analysis. 

Don't auto update or let others update your programs without leaving some kind of documentation. Also, record metadata such as version or release information, operating system run on, and any other data that could help exactly reproduce your findings.

**Comment by kubu4** [comment]
A package update between the previous analysis and a repeated analysis changed how the data was analyzed (within the R package).

Documenting (and paying attention to) software versions is critical for reproducibility.

**Comment by lisa418** [comment]
Using an updated version of R. Lesson here is that replication not only relies on data and codes but also software versions and dates of analysis which is why it is important that all of these metadata details are well documented.

**Comment by jldimond** [comment]
The R package had been updated since the initial analyses. This example illustrates the importance of scrupulously documenting everything--including software versions--in your read me file or metadata.
