### ISSUE TITLE
[quiz] Golden Rule

### ISSUE THREAD

**Issue by sr320** [sr320/fish546-2015#9]
What is the Golden Rule of Bioinformatics?

**Comment by willking2** [comment]
Don't trust your tools or your data

**Comment by jheare** [comment]
Always re-run your program or script multiple times to ensure reproducible results and avoid single use errors. Don't trust that you or someone else's script/program will work properly even if it generates an output. Don't trust that your data or outputs from it are free of error.

**Comment by kubu4** [comment]
Don't trust your tools or your data.  Make sure to have checks/intermediate steps to evaluate accuracy of process.

**Comment by lisa418** [comment]
Never EVER trust your tools or data. Garbage in, garbage out!

**Comment by jldimond** [comment]
Being the last to post, my thunder has been stolen so I will attempt to paraphrase: CAUTION
